name: CI/CD

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.63.0-noble
      options: --user 1001
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # https://github.com/actions/checkout/releases/tag/v7.0.1
      - name: Setup pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # https://github.com/pnpm/setup/releases/tag/v3.0.0
        with:
          version: 12
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test (types)
        run: pnpm run test:types
      - name: Test (lint)
        run: pnpm run test:lint
      - name: Build
        run: pnpm run build
      - name: Test (e2e)
        run: pnpm run test:e2e
      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # https://github.com/actions/upload-pages-artifact/releases/tag/v5.0.0
        with:
          path: ./dist/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # https://github.com/actions/deploy-pages/releases/tag/v5.0.1
